"""
modules/nikto_scanner.py — Nikto Integration

Web server scanner for Security Misconfiguration assessment.

Project scope:
- Missing HTTP Security Headers
- Sensitive File and Directory Exposure
- Unsafe HTTP Methods
- Outdated Software Versions
- Information Disclosure via Server Banners
- Exposed Admin / Management Interfaces

Note: SSL/TLS findings are intentionally NOT generated by this module.
testssl_scanner.py is the single source of truth for SSL/TLS
(Weak SSL/TLS and Cipher Configurations) to avoid duplicate findings
across tools for the same risk category.

The main project focus is OWASP Top 10 A02:2025
(Security Misconfiguration).
"""

import json
import logging
import os
import re
from typing import Dict, Any, List

from modules.runner import run_tool
import config


logger = logging.getLogger("assessor.nikto")


# ---------------------------------------------------------------------------
# Project scope
# ---------------------------------------------------------------------------

OWASP_CATEGORY = "A02:2025 - Security Misconfiguration"


# Findings outside the main project scope are not included in the
# final Nikto findings.
# "Default Configuration" and "Web Misconfiguration" were removed:
# they acted as catch-all buckets not mapped to any of the project's
# 8 defined risks, and let unrelated findings pass the filter.
# "SSL/TLS" was removed: testssl_scanner.py owns this risk category
# to avoid duplicate findings between tools.
IN_SCOPE_CATEGORIES = {
    "Security Headers",
    "Sensitive Files",
    "Directory Exposure",
    "Admin Exposure",
    "Information Disclosure",
    "Outdated Software",
    "HTTP Methods",
}


# ---------------------------------------------------------------------------
# Nikto scanner
# ---------------------------------------------------------------------------

def scan(url: str, output_dir: str) -> Dict[str, Any]:
    """
    Run Nikto against the target URL.

    Nikto is configured to focus on misconfiguration and default files,
    which matches the main scope of the project.
    """

    os.makedirs(output_dir, exist_ok=True)

    out_json = os.path.join(output_dir, "nikto_results.json")

    cmd = [
        config.TOOL_PATHS["nikto"],
        "-h", url,
        "-Format", "json",
        "-output", out_json,
        "-nointeractive",

        # Tuning 2 focuses on misconfiguration/default files.
        "-Tuning", "2",

        "-timeout", "5",
    ]

    logger.info("[nikto] Starting scan: %s", url)

    rc, stdout, stderr = run_tool(
        cmd,
        "nikto",
        timeout=config.TIMEOUTS["nikto"]
    )

    result = {
        "tool": "nikto",
        "status": (
            "success"
            if rc == 0
            else ("timeout" if rc == -1 else "error")
        ),
        "url": url,
        "findings": [],
        "raw_output": stdout + stderr,
    }

    # -----------------------------------------------------------------------
    # Parse JSON output
    # -----------------------------------------------------------------------

    json_file_to_parse = None

    if os.path.exists(out_json):
        json_file_to_parse = out_json

    elif os.path.exists(out_json + ".json"):
        json_file_to_parse = out_json + ".json"

    if json_file_to_parse:
        try:
            result["findings"] = _parse_nikto_json(
                json_file_to_parse
            )

        except Exception as exc:
            logger.warning(
                "[nikto] Failed to parse JSON output: %s",
                exc
            )

            result["findings"] = _parse_nikto_text(stdout)

    # -----------------------------------------------------------------------
    # Fallback to text output
    # -----------------------------------------------------------------------

    if not result["findings"] and stdout:
        result["findings"] = _parse_nikto_text(stdout)

    logger.info(
        "[nikto] Completed: %d in-scope findings",
        len(result["findings"])
    )

    return result


# ---------------------------------------------------------------------------
# JSON parser
# ---------------------------------------------------------------------------

def _parse_nikto_json(json_file: str) -> List[Dict]:
    """
    Parse Nikto JSON output.

    Supports several Nikto JSON structures:
    - {"vulnerabilities": [...]}
    - {"host": {"vulnerabilities": [...]}}
    - {"hosts": [{"vulnerabilities": [...] }]}
    - [{"vulnerabilities": [...]}]
    """

    with open(
        json_file,
        "r",
        encoding="utf-8",
        errors="replace"
    ) as f:
        content = f.read().strip()

    if not content:
        return []

    json_positions = [
        pos
        for pos in (
            content.find("["),
            content.find("{")
        )
        if pos != -1
    ]

    if json_positions:
        content = content[min(json_positions):]

    data = json.loads(content)

    vulns = []

    if isinstance(data, dict):

        vulns = data.get("vulnerabilities", [])

        if not vulns and isinstance(data.get("host"), dict):
            vulns = data["host"].get(
                "vulnerabilities",
                []
            )

        if not vulns and isinstance(data.get("hosts"), list):

            for host_obj in data["hosts"]:

                if isinstance(host_obj, dict):

                    host_vulns = host_obj.get(
                        "vulnerabilities",
                        []
                    )

                    if isinstance(host_vulns, list):
                        vulns.extend(host_vulns)

    elif isinstance(data, list):

        for host_obj in data:

            if not isinstance(host_obj, dict):
                continue

            host_vulns = host_obj.get(
                "vulnerabilities",
                []
            )

            if isinstance(host_vulns, list):
                vulns.extend(host_vulns)

    findings = []

    for vuln in vulns:

        if not isinstance(vuln, dict):
            continue

        osvdb = str(
            vuln.get(
                "OSVDBID",
                vuln.get(
                    "OSVDB",
                    vuln.get(
                        "osvdb",
                        vuln.get("id", "0")
                    )
                )
            )
        )

        msg = vuln.get(
            "msg",
            vuln.get(
                "message",
                vuln.get(
                    "description",
                    ""
                )
            )
        )

        uri = vuln.get(
            "uri",
            vuln.get(
                "url",
                vuln.get(
                    "path",
                    ""
                )
            )
        )

        method = vuln.get(
            "method",
            "GET"
        )

        msg = str(msg).strip()
        uri = str(uri).strip()

        if not msg:
            continue

        category = _classify_nikto_category(msg)

        # Keep only findings related to the project scope.
        if category not in IN_SCOPE_CATEGORIES:
            logger.debug(
                "[nikto] Ignored out-of-scope finding: %s",
                msg
            )
            continue

        severity = _classify_nikto_severity(
            msg,
            category
        )

        finding = _build_finding(
            title=_clean_nikto_title(msg),
            severity=severity,
            description=msg,
            evidence=(
                f"{method} {uri}"
                if uri
                else msg[:200]
            ),
            category=category,
            osvdb=osvdb,
        )

        findings.append(finding)

    return findings


# ---------------------------------------------------------------------------
# Text parser
# ---------------------------------------------------------------------------

def _parse_nikto_text(stdout: str) -> List[Dict]:
    """
    Fallback parser for Nikto plain-text output.
    """

    findings = []

    finding_pattern = re.compile(
        r"^\+\s+(.+)$",
        re.MULTILINE
    )

    for match in finding_pattern.finditer(stdout):

        line = match.group(1).strip()

        if not line:
            continue

        if any(
            skip in line.lower()
            for skip in [
                "target ip",
                "target hostname",
                "target port",
                "start time",
                "end time",
                "host(s) tested",
                "requests made",
            ]
        ):
            continue

        category = _classify_nikto_category(line)

        if category not in IN_SCOPE_CATEGORIES:
            continue

        severity = _classify_nikto_severity(
            line,
            category
        )

        finding = _build_finding(
            title=_clean_nikto_title(line),
            severity=severity,
            description=line,
            evidence=line[:200],
            category=category,
            osvdb="0",
        )

        findings.append(finding)

    return findings


# ---------------------------------------------------------------------------
# Finding builder
# ---------------------------------------------------------------------------

def _build_finding(
    title: str,
    severity: str,
    description: str,
    evidence: str,
    category: str,
    osvdb: str = "0",
) -> Dict[str, Any]:
    """
    Create a standardized finding object.

    CVSS vector is retrieved from the project's configuration.
    The actual CVSS score calculation should be handled by the
    project's risk/CVSS module.
    """

    finding = {
        "tool": "nikto",
        "title": title,
        "severity": severity,
        "description": description,
        "evidence": evidence,
        "category": category,
        "owasp_category": OWASP_CATEGORY,
        "osvdb": osvdb,
    }

    if severity != "INFO":

        finding["cvss_vector"] = (
            config.DEFAULT_CVSS_VECTORS.get(
                severity,
                config.DEFAULT_CVSS_VECTORS.get(
                    "MEDIUM",
                    ""
                )
            )
        )

    else:
        finding["cvss_vector"] = ""

    return finding


# ---------------------------------------------------------------------------
# Severity classification
# ---------------------------------------------------------------------------

def _classify_nikto_severity(
    msg: str,
    category: str
) -> str:
    """
    Classify severity using the finding category and message.
    """

    msg_lower = msg.lower()

    if category == "Information Disclosure":

        if any(
            keyword in msg_lower
            for keyword in [
                "server banner",
                "version disclosed",
                "server:",
                "x-powered-by",
            ]
        ):
            return "INFO"

    if "robots.txt" in msg_lower:
        return "INFO"

    if any(
        keyword in msg_lower
        for keyword in [
            "remote code execution",
            "remote code",
            "command injection",
            "authentication bypass",
            "default credentials",
            "admin password",
            "webshell",
            "backdoor",
        ]
    ):
        return "CRITICAL"

    if any(
        keyword in msg_lower
        for keyword in [
            "exposed credentials",
            "arbitrary file",
            "file inclusion",
            "local file inclusion",
            "remote file inclusion",
            "directory traversal",
            "path traversal",
            "unrestricted upload",
            "sensitive file",
            "backup file",
            "configuration file",
            "config file",
        ]
    ):
        return "HIGH"

    if category == "Sensitive Files":
        return "HIGH"

    # HTTP Methods severity
    if category == "HTTP Methods":
        if any(m in msg_lower for m in ["put", "delete", "webdav"]):
            return "HIGH"
        return "MEDIUM"

    if category == "Admin Exposure":
        return "MEDIUM"

    if category == "Directory Exposure":
        return "MEDIUM"

    if category == "Information Disclosure":
        return "MEDIUM"

    if category == "Outdated Software":
        return "MEDIUM"

    if any(
        keyword in msg_lower
        for keyword in [
            "directory listing",
            "directory index",
            "phpinfo",
            "server-status",
            "server-info",
            "debug",
            "stack trace",
            "configuration",
            "backup",
        ]
    ):
        return "MEDIUM"

    if category == "Security Headers":
        return "LOW"

    if any(
        keyword in msg_lower
        for keyword in [
            "header",
            "cookie",
            "missing",
            "outdated",
            "deprecated",
            "insecure",
            "redirect",
            "clickjacking",
        ]
    ):
        return "LOW"

    return "INFO"


# ---------------------------------------------------------------------------
# Category classification
# ---------------------------------------------------------------------------

def _classify_nikto_category(msg: str) -> str:
    """
    Map a Nikto finding to one of the project's security categories.
    """

    msg_lower = msg.lower()

    # -----------------------------------------------------------------------
    # Security Headers
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "security header",
            "http header",
            "x-frame-options",
            "x-content-type-options",
            "content-security-policy",
            "strict-transport-security",
            "referrer-policy",
            "permissions-policy",
            "hsts",
            "clickjacking",
        ]
    ):
        return "Security Headers"

    # -----------------------------------------------------------------------
    # Sensitive Files
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            ".env",
            ".git",
            ".svn",
            ".hg",
            ".htpasswd",
            ".htaccess",
            "backup file",
            "config file",
            "configuration file",
            "sensitive file",
            ".bak",
            ".zip",
            ".sql",
            ".dump",
            ".tar",
            ".gz",
            ".rar",
        ]
    ):
        return "Sensitive Files"

    # -----------------------------------------------------------------------
    # Directory Exposure
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "directory listing",
            "directory index",
            "directory browsing",
            "directory exposed",
            "index of",
        ]
    ):
        return "Directory Exposure"

    # -----------------------------------------------------------------------
    # Admin / Management Exposure
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "admin panel",
            "administrative interface",
            "management interface",
            "phpmyadmin",
            "webmin",
            "administrator",
            "control panel",
        ]
    ):
        return "Admin Exposure"

    # -----------------------------------------------------------------------
    # Unsafe HTTP Methods
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "put method",
            "delete method",
            "trace method",
            "allowed methods",
            "http method",
            "cross-site tracing",
            "xst",
            "webdav",
        ]
    ):
        return "HTTP Methods"

    # -----------------------------------------------------------------------
    # Information Disclosure
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "server banner",
            "server information",
            "server-info",
            "server-status",
            "version disclosed",
            "information disclosure",
            "x-powered-by",
            "robots.txt",
        ]
    ):
        return "Information Disclosure"

    # -----------------------------------------------------------------------
    # Outdated Software
    # -----------------------------------------------------------------------

    if any(
        keyword in msg_lower
        for keyword in [
            "outdated",
            "obsolete",
            "old version",
            "deprecated version",
            "version is old",
        ]
    ):
        return "Outdated Software"

    # -----------------------------------------------------------------------
    # Out of scope
    # -----------------------------------------------------------------------

    if "sql" in msg_lower:
        return "Injection"

    if "xss" in msg_lower or "cross-site scripting" in msg_lower:
        return "XSS"

    if "command injection" in msg_lower:
        return "Injection"

    if "remote code" in msg_lower or "rce" in msg_lower:
        return "Remote Code Execution"

    if any(
        keyword in msg_lower
        for keyword in ["ssl", "tls", "certificate", "cipher"]
    ):
        # SSL/TLS is intentionally out of scope for Nikto —
        # handled exclusively by testssl_scanner.py
        return "SSL/TLS (excluded — see testssl_scanner)"

    return "Other"


# ---------------------------------------------------------------------------
# Title cleanup
# ---------------------------------------------------------------------------

def _clean_nikto_title(msg: str) -> str:
    """
    Clean Nikto message and limit title length to 80 characters.
    """

    msg = re.sub(
        r"OSVDB-\d+:\s*",
        "",
        msg,
        flags=re.IGNORECASE
    )

    msg = re.sub(
        r"^\+\s*",
        "",
        msg
    )

    msg = msg.strip()

    if len(msg) > 80:
        msg = msg[:77] + "..."

    return msg
